[project]
name = "carnum"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "opencv-python>=4.12.0.88",
    "pygobject>=3.54.5",
    "pyside6>=6.10.0",
    "pytesseract>=0.3.13",
]

[tool.ruff]
ignore = ["E701"]
